### ISSUE TITLE
Can not run example - provision not working?

### ISSUE THREAD

**Issue by SimonDeussen** [holbertonschool/deep-learning-vagrant-machine#4]
Hi,
thank you so much for all the effort you put into this vm!
Unfortunatly, I can't get it to work. I downloaded the repo, extracted it into a folder und ran vagrant.
After connecting with putty i tryied to run the example provided.

```
vagrant@deep-learning:~$ python keras/examples/addition_rnn.py                  Using TensorFlow backend.
Generating data...
Total addition questions: 50000
Vectorization...
Training Data:
(45000, 7, 12)
(45000, 4, 12)
Validation Data:
(5000, 7, 12)
(5000, 4, 12)
Build model...
Traceback (most recent call last):
  File "keras/examples/addition_rnn.py", line 154, in <module>
    model.add(RNN(HIDDEN_SIZE, input_shape=(MAXLEN, len(chars))))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 430, in add
    layer(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 257, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 551, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 994, in build
    K.set_value(self.bias, bias_value)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2000, in set_value
    get_session().run(assign_op, feed_dict={assign_placeholder: value})
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 155, in get_session
    _initialize_variables()
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 300, in _initialize_variables
    variables = tf.global_variables()
AttributeError: 'module' object has no attribute 'global_variables'
```

I have installed the latest versions of vagrant & virtualBox, running it on WIN 10 Pro 1607.
Destroyed the vm several time and tryied redownloading it, but it did not fix the problem.
Where could i start solving this?

Thank you for taking the Time, Simon

**Comment by pconnolly-rll** [comment]
Thanks for taking the time to put this VM together, but I'm getting the same error as well.

**Comment by greenspray9** [comment]
I also encounter similar error when running the keras example. `TypeError: Expected int32, got list containing Tensors of type '_Message' instead.`. Any clue?

**Comment by ocuil** [comment]
Hi there guys !!! I have the same error ... anybody have idea ?
Thanks and Happy New Year !!!
